// <auto-generated />
namespace BugTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MakeFewTicketPropertiesNullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MakeFewTicketPropertiesNullable));
        
        string IMigrationMetadata.Id
        {
            get { return "202106151751210_MakeFewTicketPropertiesNullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
